system("python3 --version")
system("pip --version")
system("pip3 --version")
system("git status")
system("git branch -a")
system("git remote -v")
system("wget", "https://bootstrap.pypa.io/pip/3.6/get-pip.py")
system("python3 get-pip.py")
system("pip --version")
system("find / -name pip -executable -type f")
